# Created 2019-08-01 Thu 17:55
#+TITLE: Read Me
#+AUTHOR: Eduardo Robles

* Graduation Degree Plan

** What is this project?
The purpose of this project is to create a versatile "Graduation Degree Plan"
for college students. Many times it can be overwhelming understanding the
requirements to graduate. So this template is meant to be a place to place all
this information.

** Why create this template?
I am a returning college student and when I first graduated college I felt glad it
was over. But later on I felt bummed because I could have done better. I was a
bit disorganized with my degree plan and for that reason I created this
template.

** What can I do with this template?
You can keep track of important information such as a copy of your degree plan,
important dates, and your course schedule. Other bits of information you can
keep track are financial aid information, books, software purchases.

Templates:
1. School.org
   - A template to keep track of your courses, credit hours, finacial aid,
     important dates, books, software.
1. Class.org
   - A template to keep your notes organized per course
2. Talk.org
   - A *Reveal JS* template for any presentations you create for a course
3. Paper.org
   - A template for any term paper you may write for a class.

** How can I help?
You send a pull request! Or buy me a [[https://ko-fi.com/mrerwtc][coffee]]!

* Todo

- [X] Create Github repo
- [X] Create README
- [] Add ~license~
- [] Add ~funding.yml~
- [] Create "Capture Templates"
  - [] Notes
  - [] Proposed Course Schedule
  - [] Registered Course Schedule
  - [] Final Grades
- [] Create a CSS template for ~talks~
- [] Add image examples to ~talks~ and ~papers~.
